parameters:
    gt_imagine.imagine.class: GT\ImagineBundle\Service\ImagineService

services:
    gt_imagine.twig.imagine_extension:
        class: GT\ImagineBundle\Twig\ImagineExtension
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }

    gt_imagine:
        class: %gt_imagine.imagine.class%
        arguments: ["@service_container"]